function [draw_panel, load_panel, learn_panel, res_panel] = create_main_panels(hFig)
% CREATE_MAIN_PANELS creates gui for four main parts of the application
%   Inputs:
%       hFig = figure of the application
%   Outputs:
%       draw_panel = panel for drawing
%       load_panel = panel for loading of networks
%       learn_panel = panel for learning and visuallization
%       res_panel = panel for displaying results
draw_panel = uipanel('Parent', hFig, ...
    'Title', 'Drawing board', ...
    'BackgroundColor', 'white', ...
    'Position', [0 0 0.5 1]);

load_panel = uipanel('Parent', hFig, ...
    'Title', 'Load network', ...
    'Position', [0.5 0.8 0.5 0.2], ...
    'BackgroundColor', 'white');

learn_panel = uipanel('Parent', hFig, ...
    'Title', 'Learn network', ...
    'Position', [0.5 0.2 0.5 0.6], ...
    'BackgroundColor', 'white');

res_panel = uipanel('Parent', hFig, ...
    'Title', 'Result', ...
    'Position', [0.5 0 0.5 0.2]);
end

