function [draw_panel, load_panel, learn_panel, res_panel] = create_main_panels(hFig)
draw_panel = uipanel('Parent', hFig, ...
    'Title', 'Drawing board', ...
    'BackgroundColor', 'white', ...
    'Position', [0 0 0.5 1]);

load_panel = uipanel('Parent', hFig, ...
    'Title', 'Load network', ...
    'Position', [0.5 0.8 0.5 0.2], ...
    'BackgroundColor', 'white');

learn_panel = uipanel('Parent', hFig, ...
    'Title', 'Learn network', ...
    'Position', [0.5 0.2 0.5 0.6], ...
    'BackgroundColor', 'white');

res_panel = uipanel('Parent', hFig, ...
    'Title', 'Result', ...
    'Position', [0.5 0 0.5 0.2]);
end

