function prepare_load_panel(load_panel, new_game_callback, save_game_callback, load_game_callback)
path_text = uicontrol('Parent', load_panel, ...
    'Style', 'edit', ...
    'Units', 'normalized', ...
    'String', fullfile(pwd, 'test.mat'), ...
    'Callback', @(src, ~, ~) check_file_exists(src.String));
e = path_text.Extent;
path_text.Position = [0.05 2/3 - e(4) / 2 2/3 e(4)];

browse_button = uicontrol('Parent', load_panel, ...
    'Style', 'pushbutton', ...
    'Units', 'normalized', ...
    'String', 'Browse...', ...
    'Callback', @browse_function);
e = browse_button.Extent;
browse_button.Position = [3/4 2/3 - e(4) / 2 7/32 e(4)];

warning_text = uicontrol('Parent', load_panel, ...
    'Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0 0 0 0], ...
    'String', '', ...
    'BackgroundColor', 'white', ...
    'ForegroundColor', 'red');

    function ret = check_file_exists(fullname)
        ret = exist(fullname, 'file') == 2;
        if ~ret
            warning_text.String = 'Selected file doesn''t exist!';
            e = warning_text.Extent;
            warning_text.Position = [0.05 1/3 - e(4) / 1.5 2/3 e(4)];
        else
            warning_text.String = '';
        end
    end
        
    function browse_function(~, ~)
        [fname , fpath] = uigetfile('*.mat','Select the data file');
        fullname = fullfile(fpath, fname);
        if fname ~= 0
            path_text.String = fullname;
        end
    end

new_button = uicontrol('Parent', load_panel, ...
    'Style', 'pushbutton', ...
    'Units', 'normalized', ...
    'String', 'New', ...
    'Callback', @(~, ~) new_game_callback());
e = new_button.Extent;
new_button.Position = [1/2 1/3 - e(4) / 2 3/32 e(4)];

load_button = uicontrol('Parent', load_panel, ...
    'Style', 'pushbutton', ...
    'Units', 'normalized', ...
    'String', 'Load', ...
    'Callback', @(~, ~) load_game_callback(path_text.String));
e = load_button.Extent;
load_button.Position = [3/4 1/3 - e(4) / 2 3/32 e(4)];

save_button = uicontrol('Parent', load_panel, ...
    'Style', 'pushbutton', ...
    'Units', 'normalized', ...
    'String', 'Save', ...
    'Callback', @(~, ~) save_game_callback(path_text.String));
e = save_button.Extent;
save_button.Position = [7/8 1/3 - e(4) / 2 e(3) e(4)];
end

